pipeline {
    agent any

    tools {
        maven 'M3'
        jdk 'jdk21'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'master', url: 'https://github.com/Badarinath15122001/Capstone-NopCommerce.git'
            }
        }

        stage('Build and Run Single Test') {
            steps {
                dir('Automation') {
                    echo 'Running only LoginTest...'
                    // Run just one test class
                    bat 'mvn -Dtest=tests.LoginTest test'
                }
            }
        }

        stage('Publish Reports') {
            steps {
                dir('Automation') {
                    echo 'Publishing HTML reports...'
                    publishHTML(target: [
                        reportDir: 'test-output',
                        reportFiles: 'emailable-report.html',
                        reportName: 'TestNG Report'
                    ])

                    publishHTML(target: [
                        reportDir: 'target/cucumber-reports',
                        reportFiles: 'cucumber-report.html',
                        reportName: 'Cucumber Report'
                    ])

                    
                }
            }
        }
    }

    post {
        always {
            dir('Automation') {
                archiveArtifacts artifacts: '**/Screenshots/*.png', allowEmptyArchive: true
                junit '**/test-output/junitreports/*.xml'
            }
        }
    }
}
